### ISSUE TITLE
Additional Children for Flatiron Institute

### ISSUE THREAD

**Issue by jdalcanton** [adsabs/CanonicalAffiliations#8]
The Flatiron Institute has a number of distinct divisions that are equivalent of academic departments and that should be disaggregated.  It would be helpful to add children to "Flatiron Inst" as follows

CCA -- Center for Computational Astrophysics
CCQ -- Center for Computational Quantum Physics
CCM -- Center for Computational Mathematics

**Comment by csgrant00** [comment]
Agreed.
